version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: mantuliak/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: mantuliak/kittygram_frontend 
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: mantuliak/kittygram_gateway 
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      backend:
        condition: service_healthy
