version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: mantuliak/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
  frontend:
    image: mantuliak/kittygram_frontend 
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
      - media:/media
  gateway:
    image: mantuliak/kittygram_gateway 
    ports:
      - 9000:80
    volumes:
      - static:/static
    depends_on:
      - backend
