version: '3'

x-pg_envs: &pg_envs
  - POSTGRES_USER=${POSTGRES_USER}
  - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  - POSTGRES_DB=${POSTGRES_DB}
  - POSTGRES_HOST=${POSTGRES_HOST}
  - POSTGRES_PORT=${POSTGRES_PORT}

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    environment:
      <<: *pg_envs
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: mantuliak/kittygram_backend
    environment:
      <<: *pg_envs
    volumes:
      - static:/backend_static
  frontend:
    image: mantuliak/kittygram_frontend 
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: mantuliak/kittygram_gateway 
    ports:
      - 9000:80
    volumes:
      - static:/static
